name: my_game
description: A new Flutter Flame game project
publish_to: 'none' # Remove this if publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.35.7"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.34.0
  flame_audio: ^2.0.0
  flame_forge2d: ^0.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   -  assets/images/
   -  assets/audio/
